### ISSUE TITLE
It works, but somehow breaks display support via thunderbolt on my hardware

### ISSUE THREAD

**Issue by proudhon** [rykdesjardins/fix-UX6404VI-audio-linux#2]
I successfully compiled the arch linux fork of the kernel following your guide and adapting it to the procedures found in the arch wiki.

Somehow booting from the patched kernel inhibits video output via thunderbolt.
Could have something to do with the nvidia drivers?
Should i recompile while having nvidia-dkms instead of nvidia?

Does thunderbolt video output works on your device?

Thanks for your work anyway.

**Comment by rykdesjardins** [comment]
Hey @proudhon, thanks for reporting this.

I tested with an external display through thunderbolt and it seems to be working properly, but I'm currently using the proprietary package `nvidia-driver-535`. On my end, I had the drivers installed before patching the kernel, and didn't have to disable the nouveau drivers.

Grub is almost unedited, too : 

```
GRUB_DEFAULT=0
GRUB_TIMEOUT_STYLE=hidden
GRUB_TIMEOUT=10
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
GRUB_CMDLINE_LINUX=""

GRUB_EARLY_INITRD_LINUX_CUSTOM="ux6404vi_cirrus_patch.cpio"
```

Can't find the article, but I've read about an Asus laptop that would try to use video output solely for audio when a peripheral was plugged in, and it made video output impossible. Maybe it's a similar case?

Sorry I can't be more helpful, I haven't worked with Arch that much-- But I wouldn't be surprised if the nvidia driver was the culprit

**Comment by proudhon** [comment]
I confirm it works with nvidia-dkms.
The audio is weak but at least it works.
Thanks a lot!
