### ISSUE TITLE
Distorted sound with asus-linux firmware

### ISSUE THREAD

**Issue by nicwands** [rykdesjardins/fix-UX6404VI-audio-linux#3]
First of all, thank you so much for your work on this!

I just wanted to note that before applying your patch, I had followed the guide [here](https://asus-linux.org/wiki/cirrus-amps/) including the part where I grabbed the firmware from their [repo](https://gitlab.com/asus-linux/firmware) according to the subsystem id on my device.

After applying your patch with that firmware installed, my sound worked but was very distorted and my speakers started getting very hot. I think they would've gotten damaged if I ran them for very long. Now that I removed the firmware though, everything is working perfectly. 

Feel free to close this, I just wanted to make note of it in case anyone else had the same problem!

**Comment by rykdesjardins** [comment]
Hey @nicwands, thanks for kind words!

The repo you linked should have done the trick, but it is very possible it might be damaging the hardware if it differs from the Windows OEM. Do you happen do still have your pre-installed Windows partition? 

You can find the `bin` files under `c:\windows\system`, the path will have the same subsystem ID as your laptop. Mine started with `csaudioext.inf`. 

I moved all of them to `/lib/firmware/cirrus` as root, but they need to be renamed to match the [repo](https://gitlab.com/asus-linux/firmware) naming convention. Not currently on the laptop right now, but I believe the file name ends with `V0_A0.bin` and `.wmfw` on the Windows partition. They can be used as is, and simply copied to the cirrus firmware directory on your partition. 

I can find the actual file name when I get back to the laptop if it can help!

**Comment by nicwands** [comment]
I do not have my windows partition anymore, I'll try to grab those drivers from a live-boot. I'll let you know if that works!

**Comment by rykdesjardins** [comment]
@nicwands keep me posted! I'm not sure if they'd only be present in the OEM version, or if a stock build would find and install the right ones. 

If not, I can always upload them to Google Drive and share the link in the `README`.

**Comment by nicwands** [comment]
Hey @rykdesjardins I'm having trouble getting windows installed again on my machine, if you could upload them that would be super helpful!

**Comment by rykdesjardins** [comment]
@nicwands Here's a tar archive with the files extracted from my laptop : https://drive.google.com/file/d/1YPp6EyA4-mJWJnVyc_PnJxqKHGXB8Fdz/view?usp=sharing

shasum 256 : `21d80332b578fc9c63d8ad4d7c082b1aded0e36b003270b57f3954d9e159cd5f  asus_UX6404VI_audio_firmware.tar.gz`

They were extracted and renamed from the Windows OEM partition, so they should behave the same way provided we have the same laptop model :crossed_fingers: 

Simply move all the files from the archive (including the symlinks) to `/lib/firmware/cirrus` and it should do the trick.

I'm still a stranger online ; feel free to verify those files on a temporary linux partition before installing on main. 

Let me know if it helps!

**Comment by nicwands** [comment]
Perfect thank you, that worked great! I'm closing this now.
